### PR TITLE
ENYO-2904: replace dependency on `node-unzip` by `node-zip`|`JSZip`

### PR DESCRIPTION
**Pull request by asnowfix**
- no more stream-based unzipping: the entire ZIP archive is now loaded
  in memory (as a Buffer).
- note to reviewer: `_unzipFile()` is indeed kept as a single function (even with multiple nested `async.*`) to keep it on a single page.

Enyo-DCO-1.1-Signed-off-by: Francois-Xavier KOWALSKI francois-xavier.kowalski@hp.com

### CODE REVIEW

**Comment by yves-del-medico** [comment]
It looks like we have garbage when creating a new project from a template file (diff done with manually extracted bootplate.zip)

> Binary files bootplate-latest/lib/onyx/samples/assets/enyo-logo-small.png and ../TODEL-LATEST/lib/onyx/samples/assets/enyo-logo-small.png differ
> Binary files bootplate-latest/lib/onyx/samples/assets/fish_bowl.png and ../TODEL-LATEST/lib/onyx/samples/assets/fish_bowl.png differ
> Binary files bootplate-latest/lib/onyx/samples/assets/menu-icon-bookmark.png and ../TODEL-LATEST/lib/onyx/samples/assets/menu-icon-bookmark.png differ
> Binary files bootplate-latest/lib/onyx/samples/assets/search-input-search.png and ../TODEL-LATEST/lib/onyx/samples/assets/search-input-search.png differ

**Comment by asnowfix** [comment]
@yves-del-medico fix binary files. Ready to review & merge.

**Comment by yves-del-medico** [comment]
I see the following error at project creation time:

> ares WARN genZip http Generator#_fetchFile() GET http://nightly.enyojs.com/latest/bootplate-latest.zip => /var/folders/nd/v6zrbf7d3jsb84vn93r4g4300000gq/T/com.enyojs.ares.generator113719-6405-u4lqxo.d/archive
> ares WARN genZip 
> ares WARN genZip genZip ERR! errorHandler():  Error: ENOENT, open 'bootplate/api/api-tool-2013_08_19-03_02_23AM/assets/api-manifest.json'

**Comment by asnowfix** [comment]
Indeed, a higher verbosity shows the same issue. Very likely an async issue between `fs.mkdir()` and `fs.write()`, which does not happen in a lighter test case.

```
[...]
ares WARN genZip sill Generator#_unzipFile() mkdir /tmp/com.enyojs.ares.generator113719-1396-1opdko6.d/work/bootplate/api/api-tool-2013_08_19-03_02_23AM/assets/
ares WARN genZip sill Generator#_unzipFile() file.name: bootplate/api/api-tool-2013_08_19-03_02_23AM/assets/api-manifest.json
ares WARN genZip 
ares WARN genZip sill Generator#_unzipFile() file.options: { binary: true,
ares WARN genZip sill Generator#_unzipFile()   date: Mon Aug 19 2013 03:02:52 GMT+0200 (CEST),
ares WARN genZip sill Generator#_unzipFile()   dir: false,
ares WARN genZip sill Generator#_unzipFile()   base64: false }
ares WARN genZip sill Generator#_unzipFile() write /tmp/com.enyojs.ares.generator113719-1396-1opdko6.d/work/bootplate/api/api-tool-2013_08_19-03_02_23AM/assets/api-manifest.json
ares WARN genZip 
ares WARN genZip genZip ERR! errorHandler():  Error: ENOENT, open 'bootplate/api/api-tool-2013_08_19-03_02_23AM/assets/api-manifest.json'
ares WARN genZip 
[...]
```

**Comment by asnowfix** [comment]
This was far less smart than an async issue: just a bad copy/paste between my test tool & the branch I uploaded on GitHub. Tested Ok (with `ares-project`, not only with the local test tool) on OSX/ChromeCanary.

**Comment by yves-del-medico** [comment]
Merged. Tests ok on OSX/Chrome-Canary and Win7/Chrome with nodejs 0.10.15

**Pull request merged**
