### PR TITLE
ENYO-3672: fix bugs regarding substitution

### PR DESCRIPTION
**Pull request by sparkleholic**
Changes
- added substitution.regexp for applying substitution using regexp.
- can use  substit.json, substit.vars and substit.regexp together

Enyo-DCO-1.1-Signed-off-by Junil Kim logyourself@gmail.com

### CODE REVIEW

**Comment by sparkleholic** [comment]
So sorry, I don't understand the meaning of `M.(m+1).p` , means `Major.Minor.patch` ? 
:-( 
sorry, could you explain a little more ?

**Comment by asnowfix** [comment]
Yes, sorry, this is what I had in mind: `(M)ajor.(m)inor.(p)atch`, so `M.(m+1).p` means _increase the minor version_.

**Comment by sparkleholic** [comment]
Really sorry for my poor english.. ( I 'll do improve my eng. this year !! >_< )

I still be curious about what you mean whether you suggest to increase version of ares-generator `0.3.4` from `0.2.4`  or suggest an use-case to use new method (`_applyRegexpSubstitution()`).

**Comment by asnowfix** [comment]
> increase version of ares-generator 0.3.4 from 0.2.4...

Yes

> or suggest an use-case to use new method (_applyRegexpSubstitution()).

Yes, this one being the root cause for the version bump.

**Comment by sparkleholic** [comment]
@snowfix : If you're ok, please handle this. :-)

**Pull request merged**
